name: Create Release

on:
  push:
    branches: 
      - master
      - test
      - main
env:  
  OCTOPUS_PROJECT_NAME: '118966'
  OCTOPUS_SPACE_NAME: Adam

jobs:
 build:
   name: Create Release
   runs-on: ubuntu-latest

   steps:
   - name: Create Release in Octopus Deploy
     uses: OctopusDeploy/create-release-action@v3.0.5
     with:
       api_key: ${{ secrets.API_KEY }}
       project: ${{ env.OCTOPUS_PROJECT_NAME }}
       server: ${{ secrets.OCTOPUS_URL }}
       space: ${{ env.OCTOPUS_SPACE_NAME }}
