name: Create Release

on:
  push:
    branches: 
      - master
      - test
      - main
env:  
  OCTOPUS_PROJECT_NAME: '118966'
  OCTOPUS_SPACE_NAME: Adam
  ENVIRONMENT: Development
  OCTOPUS_API_KEY: ${{ secrets.API_KEY }}   # API key used with Octopus Deploy instance
  OCTOPUS_HOST: ${{ secrets.OCTOPUS_URL }}       # address of Octopus Deploy instance (i.e. https://demo.octopus.app)     
  OCTOPUS_SPACE: 'Spaces-262'
  

jobs:
 build:
   name: Build and Push Website
   runs-on: ubuntu-latest

   steps:
   - name: Create Release in Octopus Deploy
     uses: OctopusDeploy/create-release-action@v3.0.5
     with:
       #api_key: ${{ secrets.OCTOPUS_API_KEY }}
       project: ${{ env.OCTOPUS_PROJECT_NAME }}
       #server: ${{ secrets.OCTOPUS_URL }}
       space: ${{ env.OCTOPUS_SPACE_NAME }}
