name: Create Release

on:
  push:
    branches: 
      - master
      - test
      - main
env:  
  OCTOPUS_PROJECT_NAME: 'GHA #1'
  OCTOPUS_SPACE_NAME: Adam

jobs:
 build:
   name: Create Release
   runs-on: ubuntu-latest

   steps:
   - run: git clone "https://github.com/AdamHollow49/octopGHA/"
   - run: ls -a octopGHA
   - run: ${{ github.workspace }}
   - run: ${{ github_workspace }}
   - name: Push a package to Octopus Deploy 🐙
     uses: OctopusDeploy/push-package-action@v3
     env:
        OCTOPUS_API_KEY: ${{ secrets.API_KEY }}
        OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
        OCTOPUS_SPACE: 'Adam'
     with:
      packages: |
        ${{ github.workspace }}/octopGHA/yamlTest.1.0.0.zip
 
   - name: Create Release in Octopus Deploy
     uses: OctopusDeploy/create-release-action@v3.0.5
     with:
       api_key: ${{ secrets.API_KEY }}
       project: ${{ env.OCTOPUS_PROJECT_NAME }}
       server: ${{ secrets.OCTOPUS_URL }}
       space: ${{ env.OCTOPUS_SPACE_NAME }}
      
