 - name: Create and deploy release
      uses: OctopusDeploy/create-release-action@v3.0.5
      with:
        api_key: ${{ secrets.API_KEY }}
        server: ${{ secrets.OCTOPUS_URL }}
        space: "Spaces-262"
        project: "118966"
