on:
  push
env:
  OCTOPUS_API_KEY: ${{ secrets.API_KEY  }}
  OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
  OCTOPUS_SPACE: 'Outer Space'
jobs:
  name: Create a release in Octopus Deploy 🐙
  uses: OctopusDeploy/create-release-action@v3
    with:
      project: 'MyProject' 
