name: Create Release

on:
  push:
    branches: 
      - master
      - test
      - main
env:  
  OCTOPUS_PROJECT_NAME: 'GHA #1'
  OCTOPUS_SPACE_NAME: Adam
  PROJECT_DATA: '[{"Name":"${{ env.OCTOPUS_PROJECT_NAME }}","Description":"", "ProjectGroupID":"ProjectGroups-1854","LifeCycleID":"Lifecycles-361"}]'

jobs:
 build:
   name: Create Release
   runs-on: ubuntu-latest

   steps:
   - name: Push a package to Octopus Deploy 🐙
     uses: OctopusDeploy/push-package-action@v3
     env:
        OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
        OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
        OCTOPUS_SPACE: 'Default'
     with:
        packages: |
          ${{ github.WORKSPACE }}/target/${{ env.PACKAGE_NAME }}.${{ env.PACKAGE_VERSION }}.war  
   
   - name: Create Release in Octopus Deploy
     uses: OctopusDeploy/create-release-action@v3.0.5
     with:
       api_key: ${{ secrets.API_KEY }}
       project: ${{ env.OCTOPUS_PROJECT_NAME }}
       server: ${{ secrets.OCTOPUS_URL }}
       space: ${{ env.OCTOPUS_SPACE_NAME }}
      
